automated commit: 'Running experiment'

diff --git a/workloads/Rocq/IFC/build_generator b/workloads/Rocq/IFC/build_generator
--- a/workloads/Rocq/IFC/build_generator
+++ b/workloads/Rocq/IFC/build_generator
@@ -12,13 +12,15 @@ strategy=$1
 
 # Validate the generator name by looking up `*Generator.v` in `Strategies` directory
 if [ ! -f "Strategies/$strategy"".v" ]; then
-    echo "Error: The generator name is invalid."
-    # Provide a list of valid fuzzers
-    echo "Valid generators are:"
-    for f in Strategies/*Generator.v; do
-        echo "  - $(basename $f .v)"
-    done
-    exit 1
+    if [ ! -f "Runners/$strategy""_test_runner.v" ]; then
+        echo "Error: The generator name is invalid."
+        # Provide a list of valid fuzzers
+        echo "Valid generators are:"
+        for f in Strategies/*Generator.v; do
+            echo "  - $(basename $f .v)"
+        done
+        exit 1
+    fi
 fi
 
 ocamlfind ocamlopt -linkpkg -package zarith -package unix -thread -rectypes $strategy"_test_runner.mli" $strategy"_test_runner.ml" -o $strategy"_test_runner.native"
